<p>Hello,</p>

<p>Please find attached the latest reports generated by the Asset Manager System:</p>

<ul>
    <li><strong>Inventory Summary Report</strong> (Excel)</li>
    <li><strong>Depreciation Summary Report</strong> (Excel)</li>
    <li><strong>Lifecycle Summary Report</strong> (Excel)</li>
</ul>

<p>These reports contain the most recent data available in the system.</p>

<p>If you have any questions or need further details, feel free to reach out.</p>

<p>Regards,<br>
    <strong>Asset Manager System</strong>
</p>