name: Asset Manager CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, sqlite, pdo_sqlite

      - name: Install dependencies
        working-directory: back-end
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Setup Laravel .env (SQLite)
        working-directory: back-end
        run: |
          cp .env.example .env
          php artisan key:generate

          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=:memory:" >> .env

      - name: Clear cache
        working-directory: back-end
        run: php artisan config:clear

      - name: Run migrations
        working-directory: back-end
        run: php artisan migrate --force

      - name: Run tests
        working-directory: back-end
        run: php artisan test

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: front-end/package-lock.json

      - name: Install dependencies
        working-directory: front-end
        run: npm ci

      - name: Build Vue
        working-directory: front-end
        run: npm run build
